import { Open_Sans } from 'next/font/google';
import { Lora } from 'next/font/google';
import type { Metadata } from 'next';
import './globals.css';

const openSans = Open_Sans({
  subsets: ['latin', 'cyrillic'],
  weight: ['300', '400', '600', '700'],
  variable: '--font-open-sans',
});

const lora = Lora({
  subsets: ['latin', 'cyrillic'],
  weight: ['400', '600', '700'],
  variable: '--font-lora',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className={`${openSans.variable} ${lora.variable}`} lang="ru">
      <body>{children}</body>
    </html>
  );
}
